name: real-time-bus-arrival-notifications

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

  # schedule:
 # - cron: '12 06-06 * * 1-5'

jobs:
  execute:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: install dependencies
        run: go mod download

      - name: run
        run: go run main.go
